/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useEffect, useRef } from "react";
import { useGLTF, PerspectiveCamera, useAnimations } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useThree } from "@react-three/fiber";
type ActionName =
  | "all"
  | "fingers"
  | "jump"
  | "kick"
  | "kick-to-fingers"
  | "Rain_Eyelid_Twist_Upper"
  | "Rain_Lips_Roll_Lower"
  | "Rain_WeightPaint"
  | "RIG-RainAction"
  | "RIG-rainAction";
type GLTFActions = Record<ActionName, THREE.AnimationAction>;
type GLTFResult = GLTF & {
  nodes: {
    ["GEO-rain_body"]: THREE.SkinnedMesh;
    ["GEO-rain_body001"]: THREE.SkinnedMesh;
    ["GEO-rain_jeans"]: THREE.SkinnedMesh;
    ["GEO-rain_top"]: THREE.SkinnedMesh;
    ["GEO-rain_eye_cornea"]: THREE.SkinnedMesh;
    ["GEO-rain_eyebrows"]: THREE.SkinnedMesh;
    ["GEO-rain_eyelashes"]: THREE.SkinnedMesh;
    ["GEO-rain_gums_lower_Data"]: THREE.SkinnedMesh;
    ["GEO-rain_gums_lower_Data_1"]: THREE.SkinnedMesh;
    ["GEO-rain_gums_upper_Data"]: THREE.SkinnedMesh;
    ["GEO-rain_gums_upper_Data_1"]: THREE.SkinnedMesh;
    ["GEO-rain_hair_ponytail"]: THREE.SkinnedMesh;
    ["GEO-rain_hair_strand"]: THREE.SkinnedMesh;
    ["GEO-rain_hairband"]: THREE.SkinnedMesh;
    ["GEO-rain_head"]: THREE.SkinnedMesh;
    ["GEO-rain_shoes_Data"]: THREE.SkinnedMesh;
    ["GEO-rain_shoes_Data_1"]: THREE.SkinnedMesh;
    ["GEO-rain_shoes_Data_2"]: THREE.SkinnedMesh;
    ["GEO-rain_shoes_Data_3"]: THREE.SkinnedMesh;
    ["GEO-rain_eyes"]: THREE.SkinnedMesh;
    ["GEO-rain_hair_main"]: THREE.SkinnedMesh;
    ["GEO-rain_tongue"]: THREE.SkinnedMesh;
    Cylinder: THREE.Mesh;
    Cylinder001: THREE.Mesh;
    TeethT: THREE.Bone;
    TeethB: THREE.Bone;
    ["P-BB-ChinM"]: THREE.Bone;
    ["P-GRP-Lip_TopM"]: THREE.Bone;
    ["P-BB-Chin_2L"]: THREE.Bone;
    ["P-BB-LaughLineM"]: THREE.Bone;
    ["P-BB-LaughLine_7L"]: THREE.Bone;
    ["P-GRP-Lip_BotM"]: THREE.Bone;
    ["FK-ToeL"]: THREE.Bone;
    ["DEF-COR-Shin_TopL"]: THREE.Bone;
    ["GRAB-HandL"]: THREE.Bone;
    ["P-BB-JawLine_3L"]: THREE.Bone;
    ["P-BB-Nose_3M"]: THREE.Bone;
    ["P-BB-Cheek_SneerL"]: THREE.Bone;
    ["P-BB-Cheek_3_2L"]: THREE.Bone;
    ["P-BB-Cheek_2_2L"]: THREE.Bone;
    ["P-BB-LaughLine_2L"]: THREE.Bone;
    ["P-BB-Nostril_2L"]: THREE.Bone;
    ["P-BB-Nostril_1L"]: THREE.Bone;
    ["P-BB-LaughLine_1L"]: THREE.Bone;
    ["P-BB-LaughLine_6L"]: THREE.Bone;
    ["P-BB-LaughLine_4L"]: THREE.Bone;
    ["P-BB-Cheek_2_1L"]: THREE.Bone;
    ["P-BB-Cheek_3_1L"]: THREE.Bone;
    ["P-BB-JawLine_2L"]: THREE.Bone;
    ["P-BB-LaughLine_5L"]: THREE.Bone;
    ["P-BB-Cheek_1_2L"]: THREE.Bone;
    ["P-BB-Cheek_4_2L"]: THREE.Bone;
    ["P-BB-Cheek_1_1L"]: THREE.Bone;
    ["P-GRP-Nose_Front"]: THREE.Bone;
    ["P-GRP-Lip_Top_1L"]: THREE.Bone;
    ["P-GRP-Lip_Bot_1L"]: THREE.Bone;
    Tongue_Root: THREE.Bone;
    ["N-BB-Eyelid_Top_1L"]: THREE.Bone;
    ["N-TAN-Tail-Crease_Lid_Across_1L"]: THREE.Bone;
    ["N-BB-Cheek_SneerL"]: THREE.Bone;
    ["N-TAN-FaceRing_4L"]: THREE.Bone;
    ["N-BB-Cheek_2_1L"]: THREE.Bone;
    ["N-TAN-FaceRing_5L"]: THREE.Bone;
    ["N-BB-Eyelid_Bot_5L"]: THREE.Bone;
    ["N-TAN-Cheek_4_0L"]: THREE.Bone;
    ["N-BB-EyeLid_Crease_9L"]: THREE.Bone;
    ["N-TAN-Cheek_4_1L"]: THREE.Bone;
    ["N-TAN-Eyelid_Top_1L"]: THREE.Bone;
    ["N-BB-Eyelid_Bot_1L"]: THREE.Bone;
    ["N-TAN-Eyelid_Bot_1L"]: THREE.Bone;
    ["N-TAN-Tail-Eyelid_Bot_4L"]: THREE.Bone;
    ["N-BB-EyeLid_Crease_7L"]: THREE.Bone;
    ["N-TAN-Cheek_2_1L"]: THREE.Bone;
    ["N-TAN-Cheek_2_2L"]: THREE.Bone;
    ["N-TAN-NoseCrease_2L"]: THREE.Bone;
    ["N-TAN-EyeLid_Crease_7L"]: THREE.Bone;
    ["N-TAN-EyeLid_Crease_9L"]: THREE.Bone;
    ["N-BB-Lip_Bot_BotM"]: THREE.Bone;
    ["N-TAN-Lip_Bot_Bot_1L"]: THREE.Bone;
    ["N-BB-Lip_Bot_CornerL"]: THREE.Bone;
    ["N-TAN-Tail-Lip_Bot_Bot_2L"]: THREE.Bone;
    ["N-TAN-Lip_Bot_AcrossM"]: THREE.Bone;
    ["N-BB-Lip_Bot_TopM"]: THREE.Bone;
    ["N-TAN-Tail-Lip_Bot_AcrossM"]: THREE.Bone;
    ["N-TAN-Lip_Bot_Top_1L"]: THREE.Bone;
    ["N-TAN-Tail-Lip_Bot_Top_2L"]: THREE.Bone;
    ["N-BB-Lip_Top_CornerL"]: THREE.Bone;
    ["N-TAN-Lip_Top_Top_2L"]: THREE.Bone;
    ["N-TAN-Lip_Top_Bot_2L"]: THREE.Bone;
    ["N-TAN-LaughLine_Lip_Across_1L"]: THREE.Bone;
    ["N-TAN-Tail-LaughLine_Cheek_Across_1_2L"]: THREE.Bone;
    ["N-TAN-LaughLine_Lip_Across_2L"]: THREE.Bone;
    ROOT: THREE.Bone;
    ["HNG-ThighL"]: THREE.Bone;
    ["HNG-Upperarm_ParentL"]: THREE.Bone;
    ["CTR-COR-Thumb_1L"]: THREE.Bone;
    ["TGT-Eyes"]: THREE.Bone;
    ["P-FK-Head"]: THREE.Bone;
    ["P-GRP-Lip_Bot_2L"]: THREE.Bone;
    ["P-GRP-Lip_Bot_2R"]: THREE.Bone;
    ["P-GRP-Lip_Top_2L"]: THREE.Bone;
    ["P-GRP-Lip_Top_2R"]: THREE.Bone;
    ["P-ACT-Lips_CornerL"]: THREE.Bone;
    ["P-ACT-Lips_CornerR"]: THREE.Bone;
    ["P-BB-Cheek_4_1L"]: THREE.Bone;
    ["P-BB-JawLine_1L"]: THREE.Bone;
    ["P-GRP-NostrilL"]: THREE.Bone;
    ["P-BB-Forehead-_TopM"]: THREE.Bone;
    ["GRP-Nose_Bridge2"]: THREE.Bone;
    ["P-BB-Forehead-_Top_1L"]: THREE.Bone;
    ["P-BB-Forehead-_Top_3L"]: THREE.Bone;
    ["P-BB-Forehead-_Top_2L"]: THREE.Bone;
    ["P-BB-Forehead-_1L"]: THREE.Bone;
    ["P-FK-Neck"]: THREE.Bone;
    ["P-BB-Chin_2R"]: THREE.Bone;
    ["P-BB-LaughLine_7R"]: THREE.Bone;
    ["P-BB-JawLine_3R"]: THREE.Bone;
    ["P-BB-Cheek_SneerR"]: THREE.Bone;
    ["P-BB-Cheek_3_2R"]: THREE.Bone;
    ["P-BB-Cheek_2_2R"]: THREE.Bone;
    ["P-BB-LaughLine_2R"]: THREE.Bone;
    ["P-BB-Nostril_2R"]: THREE.Bone;
    ["P-BB-Nostril_1R"]: THREE.Bone;
    ["P-BB-LaughLine_1R"]: THREE.Bone;
    ["P-BB-LaughLine_6R"]: THREE.Bone;
    ["P-BB-LaughLine_4R"]: THREE.Bone;
    ["P-BB-Cheek_2_1R"]: THREE.Bone;
    ["P-BB-Cheek_3_1R"]: THREE.Bone;
    ["P-BB-JawLine_2R"]: THREE.Bone;
    ["P-BB-LaughLine_5R"]: THREE.Bone;
    ["P-BB-Cheek_1_2R"]: THREE.Bone;
    ["P-BB-Cheek_4_2R"]: THREE.Bone;
    ["P-BB-Cheek_1_1R"]: THREE.Bone;
    ["P-GRP-Lip_Top_1R"]: THREE.Bone;
    ["P-GRP-Lip_Bot_1R"]: THREE.Bone;
    ["N-BB-Eyelid_Top_1R"]: THREE.Bone;
    ["N-TAN-Tail-Crease_Lid_Across_1R"]: THREE.Bone;
    ["N-BB-Cheek_SneerR"]: THREE.Bone;
    ["N-TAN-FaceRing_4R"]: THREE.Bone;
    ["N-BB-Cheek_2_1R"]: THREE.Bone;
    ["N-TAN-FaceRing_5R"]: THREE.Bone;
    ["N-BB-Eyelid_Bot_5R"]: THREE.Bone;
    ["N-TAN-Cheek_4_0R"]: THREE.Bone;
    ["N-BB-EyeLid_Crease_9R"]: THREE.Bone;
    ["N-TAN-Cheek_4_1R"]: THREE.Bone;
    ["N-TAN-Eyelid_Top_1R"]: THREE.Bone;
    ["N-BB-Eyelid_Bot_1R"]: THREE.Bone;
    ["N-TAN-Eyelid_Bot_1R"]: THREE.Bone;
    ["N-TAN-Tail-Eyelid_Bot_4R"]: THREE.Bone;
    ["N-BB-EyeLid_Crease_7R"]: THREE.Bone;
    ["N-TAN-Cheek_2_1R"]: THREE.Bone;
    ["N-TAN-Cheek_2_2R"]: THREE.Bone;
    ["N-BB-EyeLid_Crease_6R"]: THREE.Bone;
    ["N-TAN-NoseCrease_1R"]: THREE.Bone;
    ["N-TAN-NoseCrease_2R"]: THREE.Bone;
    ["N-TAN-EyeLid_Crease_6R"]: THREE.Bone;
    ["N-TAN-EyeLid_Crease_7R"]: THREE.Bone;
    ["N-TAN-EyeLid_Crease_9R"]: THREE.Bone;
    ["N-TAN-Lip_Bot_Bot_1R"]: THREE.Bone;
    ["N-BB-Lip_Bot_CornerR"]: THREE.Bone;
    ["N-TAN-Tail-Lip_Bot_Bot_2R"]: THREE.Bone;
    ["N-TAN-Lip_Bot_Top_1R"]: THREE.Bone;
    ["N-TAN-Tail-Lip_Bot_Top_2R"]: THREE.Bone;
    ["N-BB-Lip_Top_CornerR"]: THREE.Bone;
    ["N-TAN-Lip_Top_Top_2R"]: THREE.Bone;
    ["N-TAN-Lip_Top_Bot_2R"]: THREE.Bone;
    ["N-TAN-LaughLine_Lip_Across_1R"]: THREE.Bone;
    ["N-TAN-Tail-LaughLine_Cheek_Across_1_2R"]: THREE.Bone;
    ["N-TAN-LaughLine_Lip_Across_2R"]: THREE.Bone;
    ["P-BB-Cheek_4_1R"]: THREE.Bone;
    ["P-BB-JawLine_1R"]: THREE.Bone;
    ["P-GRP-NostrilR"]: THREE.Bone;
    ["P-BB-Forehead-_Top_1R"]: THREE.Bone;
    ["P-BB-Forehead-_Top_3R"]: THREE.Bone;
    ["P-BB-Forehead-_Top_2R"]: THREE.Bone;
    ["P-BB-Forehead-_1R"]: THREE.Bone;
    ["P-GRP-Nose_Bridge"]: THREE.Bone;
    ["CTR-COR-Thumb_2L"]: THREE.Bone;
    ["GRP-STR-Nose_Front"]: THREE.Bone;
    ["GRP-STR-NostrilL"]: THREE.Bone;
    ["GRP-STR-NostrilR"]: THREE.Bone;
    ["P-SK-Cheek_PuffL"]: THREE.Bone;
    ["P-SK-Cheek_PuffR"]: THREE.Bone;
    ["FK-ToeR"]: THREE.Bone;
    ["DEF-COR-Shin_TopR"]: THREE.Bone;
    ["GRAB-HandR"]: THREE.Bone;
    ["HNG-ThighR"]: THREE.Bone;
    ["HNG-Upperarm_ParentR"]: THREE.Bone;
    ["CTR-COR-Thumb_1R"]: THREE.Bone;
    ["CTR-COR-Thumb_2R"]: THREE.Bone;
    Root_EarL: THREE.Bone;
    Root_EarR: THREE.Bone;
    ["IK-P-Pole-ShinL"]: THREE.Bone;
    ["IK-P-Pole-ShinR"]: THREE.Bone;
    ["N-BB-Forehead-_TopM"]: THREE.Bone;
    ["N-TAN-Forehead_2M"]: THREE.Bone;
    ["N-BB-Eyebrow_TopM"]: THREE.Bone;
    ["N-TAN-Eyebrow_AcrossM"]: THREE.Bone;
    ["N-BB-Eyebrow_BotM"]: THREE.Bone;
    ["N-TAN-Nose_1M"]: THREE.Bone;
    ["N-BB-Nose_1M"]: THREE.Bone;
    ["N-TAN-Nose_2M"]: THREE.Bone;
    ["N-BB-Nose_2M"]: THREE.Bone;
    ["N-TAN-Nose_3M"]: THREE.Bone;
    ["N-BB-Nose_3M"]: THREE.Bone;
    ["N-TAN-Nose_4M"]: THREE.Bone;
    ["N-BB-Nose_4M"]: THREE.Bone;
    ["N-TAN-Nose_5M"]: THREE.Bone;
    ["N-BB-Lip_Top_TopM"]: THREE.Bone;
    ["N-TAN-Lip_Top_AcrossM"]: THREE.Bone;
    ["N-BB-Lip_Top_BotM"]: THREE.Bone;
    ["N-TAN-Tail-Lip_Top_AcrossM"]: THREE.Bone;
    ["N-BB-LaughLine_3L"]: THREE.Bone;
    ["N-TAN-NoseRing_3L"]: THREE.Bone;
    ["N-BB-LaughLine_2L"]: THREE.Bone;
    ["N-TAN-NoseRing_4L"]: THREE.Bone;
    ["N-BB-LaughLine_1L"]: THREE.Bone;
    ["N-TAN-NoseRing_5L"]: THREE.Bone;
    ["N-TAN-Tail-NoseRing_5L"]: THREE.Bone;
    ["N-TAN-NoseFront_1L"]: THREE.Bone;
    ["N-BB-Nostril_1L"]: THREE.Bone;
    ["N-TAN-NoseFront_2L"]: THREE.Bone;
    ["N-TAN-Tail-NoseFront_2L"]: THREE.Bone;
    ["N-BB-Forehead-_Top_1L"]: THREE.Bone;
    ["N-TAN-Forehead_2_2L"]: THREE.Bone;
    ["N-BB-Eyebrow_Top_1L"]: THREE.Bone;
    ["N-TAN-Eyebrow_Across_1L"]: THREE.Bone;
    ["N-BB-Eyebrow_Bot_1L"]: THREE.Bone;
    ["N-TAN-Brow_Crease_Across_2L"]: THREE.Bone;
    ["N-BB-EyeLid_Crease_2L"]: THREE.Bone;
    ["N-TAN-Crease_Lid_Across_2L"]: THREE.Bone;
    ["N-BB-Eyelid_Top_2L"]: THREE.Bone;
    ["N-TAN-Tail-Crease_Lid_Across_2L"]: THREE.Bone;
    ["N-BB-Forehead-_1L"]: THREE.Bone;
    ["N-TAN-Forehead_1_2L"]: THREE.Bone;
    ["N-BB-Eyebrow_1L"]: THREE.Bone;
    ["N-TAN-Brow_Crease_Across_1L"]: THREE.Bone;
    ["N-BB-EyeLid_Crease_1L"]: THREE.Bone;
    ["N-TAN-Crease_Lid_Across_1L"]: THREE.Bone;
    ["N-BB-Forehead-_Top_3L"]: THREE.Bone;
    ["N-TAN-Forehead_4_2L"]: THREE.Bone;
    ["N-BB-Eyebrow_Top_3L"]: THREE.Bone;
    ["N-TAN-Eyebrow_Across_3L"]: THREE.Bone;
    ["N-BB-Eyebrow_Bot_3L"]: THREE.Bone;
    ["N-TAN-FaceRing_1L"]: THREE.Bone;
    ["N-BB-NoseBridge_1L"]: THREE.Bone;
    ["N-TAN-FaceRing_2L"]: THREE.Bone;
    ["N-BB-NoseBridge_2L"]: THREE.Bone;
    ["N-TAN-FaceRing_3L"]: THREE.Bone;
    ["N-BB-Cheek_3_1L"]: THREE.Bone;
    ["N-TAN-FaceRing_6L"]: THREE.Bone;
    ["N-BB-Cheek_4_1L"]: THREE.Bone;
    ["N-TAN-FaceRing_7L"]: THREE.Bone;
    ["N-BB-Cheek_5_1L"]: THREE.Bone;
    ["N-TAN-FaceRing_8L"]: THREE.Bone;
    ["N-TAN-Eyebrow_Upper_1L"]: THREE.Bone;
    ["N-TAN-Eyebrow_Upper_2L"]: THREE.Bone;
    ["N-BB-Eyebrow_Top_2L"]: THREE.Bone;
    ["N-TAN-Eyebrow_Upper_3L"]: THREE.Bone;
    ["N-TAN-Eyebrow_Upper_4L"]: THREE.Bone;
    ["N-TAN-Tail-Eyebrow_Upper_4L"]: THREE.Bone;
    ["N-TAN-Brow_Crease_Across_4L"]: THREE.Bone;
    ["N-BB-EyeLid_Crease_4L"]: THREE.Bone;
    ["N-TAN-Crease_Lid_Across_4L"]: THREE.Bone;
    ["N-BB-Eyelid_Top_4L"]: THREE.Bone;
    ["N-TAN-Tail-Crease_Lid_Across_4L"]: THREE.Bone;
    ["N-BB-Forehead-_Top_2L"]: THREE.Bone;
    ["N-TAN-Forehead_3_2L"]: THREE.Bone;
    ["N-TAN-Eyebrow_Across_2L"]: THREE.Bone;
    ["N-BB-Eyebrow_Bot_2L"]: THREE.Bone;
    ["N-TAN-Brow_Crease_Across_3L"]: THREE.Bone;
    ["N-BB-EyeLid_Crease_3L"]: THREE.Bone;
    ["N-TAN-Crease_Lid_Across_3L"]: THREE.Bone;
    ["N-BB-Eyelid_Top_3L"]: THREE.Bone;
    ["N-TAN-Tail-Crease_Lid_Across_3L"]: THREE.Bone;
    ["N-BB-TempleL"]: THREE.Bone;
    ["N-TAN-Temple_2L"]: THREE.Bone;
    ["N-BB-JawLine_1L"]: THREE.Bone;
    ["N-TAN-JawLine_1L"]: THREE.Bone;
    ["N-BB-JawLine_2L"]: THREE.Bone;
    ["N-TAN-JawLine_2L"]: THREE.Bone;
    ["N-BB-JawLine_3L"]: THREE.Bone;
    ["N-TAN-JawLine_3L"]: THREE.Bone;
    ["N-BB-JawLine_4L"]: THREE.Bone;
    ["N-TAN-JawLine_4L"]: THREE.Bone;
    ["N-BB-JawLine_5L"]: THREE.Bone;
    ["N-TAN-JawLine_5L"]: THREE.Bone;
    ["N-BB-JawLineM"]: THREE.Bone;
    ["N-TAN-Tail-JawLine_5L"]: THREE.Bone;
    ["N-TAN-Cheek_Jawline_Across_1L"]: THREE.Bone;
    ["N-TAN-Tail-Cheek_Jawline_Across_1L"]: THREE.Bone;
    ["N-TAN-Eyelid_Top_2L"]: THREE.Bone;
    ["N-TAN-Eyelid_Top_3L"]: THREE.Bone;
    ["N-TAN-Eyelid_Top_4L"]: THREE.Bone;
    ["N-BB-Eyelid_Top_5L"]: THREE.Bone;
    ["N-TAN-Tail-Eyelid_Top_4L"]: THREE.Bone;
    ["N-BB-Eyelid_Bot_2L"]: THREE.Bone;
    ["N-TAN-Eyelid_Bot_2L"]: THREE.Bone;
    ["N-BB-Eyelid_Bot_3L"]: THREE.Bone;
    ["N-TAN-Eyelid_Bot_3L"]: THREE.Bone;
    ["N-BB-Eyelid_Bot_4L"]: THREE.Bone;
    ["N-TAN-Eyelid_Bot_4L"]: THREE.Bone;
    ["N-BB-EyeLid_Crease_5L"]: THREE.Bone;
    ["N-TAN-NoseBridge_2_2L"]: THREE.Bone;
    ["N-TAN-NoseBridge_2_3L"]: THREE.Bone;
    ["N-TAN-Tail-NoseBridge_2_3L"]: THREE.Bone;
    ["N-TAN-NoseMidLine_3L"]: THREE.Bone;
    ["N-TAN-NoseMidLine_2L"]: THREE.Bone;
    ["N-TAN-NoseMidLine_1L"]: THREE.Bone;
    ["N-BB-Lip_Top_TopL"]: THREE.Bone;
    ["N-TAN-Lip_Top_AcrossL"]: THREE.Bone;
    ["N-BB-Lip_Top_BotL"]: THREE.Bone;
    ["N-TAN-Tail-Lip_Top_AcrossL"]: THREE.Bone;
    ["N-TAN-Cheek_2_0L"]: THREE.Bone;
    ["N-BB-Cheek_2_2L"]: THREE.Bone;
    ["N-TAN-Cheek_2_3L"]: THREE.Bone;
    ["N-TAN-Tail-Cheek_2_3L"]: THREE.Bone;
    ["N-TAN-NoseCrease_0L"]: THREE.Bone;
    ["N-BB-EyeLid_Crease_6L"]: THREE.Bone;
    ["N-TAN-NoseCrease_1L"]: THREE.Bone;
    ["N-TAN-Tail-NoseCrease_2L"]: THREE.Bone;
    ["N-TAN-Cheek_3_0L"]: THREE.Bone;
    ["N-BB-EyeLid_Crease_8L"]: THREE.Bone;
    ["N-TAN-Cheek_3_1L"]: THREE.Bone;
    ["N-TAN-Cheek_3_2L"]: THREE.Bone;
    ["N-BB-Cheek_3_2L"]: THREE.Bone;
    ["N-TAN-Cheek_Jawline_Across_3L"]: THREE.Bone;
    ["N-TAN-Tail-Cheek_Jawline_Across_3L"]: THREE.Bone;
    ["N-BB-EyeLid_Crease_10L"]: THREE.Bone;
    ["N-TAN-Cheek_5_1L"]: THREE.Bone;
    ["N-TAN-Cheek_5_2L"]: THREE.Bone;
    ["N-TAN-Tail-Cheek_5_2L"]: THREE.Bone;
    ["N-TAN-Cheek_4_2L"]: THREE.Bone;
    ["N-BB-Cheek_4_2L"]: THREE.Bone;
    ["N-TAN-Cheek_4_3L"]: THREE.Bone;
    ["N-TAN-Tail-Cheek_4_3L"]: THREE.Bone;
    ["N-TAN-Eyebrow_Lower_1L"]: THREE.Bone;
    ["N-TAN-Eyebrow_Lower_2L"]: THREE.Bone;
    ["N-TAN-Eyebrow_Lower_3L"]: THREE.Bone;
    ["N-TAN-Eyebrow_Lower_4L"]: THREE.Bone;
    ["N-TAN-Tail-Eyebrow_Lower_4L"]: THREE.Bone;
    ["N-BB-Lip_Bot_BotL"]: THREE.Bone;
    ["N-TAN-Lip_Bot_AcrossL"]: THREE.Bone;
    ["N-BB-Lip_Bot_TopL"]: THREE.Bone;
    ["N-TAN-Tail-Lip_Bot_AcrossL"]: THREE.Bone;
    ["N-TAN-EyeLid_Crease_4L"]: THREE.Bone;
    ["N-TAN-EyeLid_Crease_5L"]: THREE.Bone;
    ["N-TAN-EyeLid_Crease_6L"]: THREE.Bone;
    ["N-TAN-EyeLid_Crease_8L"]: THREE.Bone;
    ["N-TAN-EyeLid_Crease_10L"]: THREE.Bone;
    ["N-TAN-EyeLid_Crease_1L"]: THREE.Bone;
    ["N-TAN-EyeLid_Crease_2L"]: THREE.Bone;
    ["N-TAN-EyeLid_Crease_3L"]: THREE.Bone;
    ["N-TAN-NoseBridge_1_2L"]: THREE.Bone;
    ["N-TAN-NoseBridge_1_1L"]: THREE.Bone;
    ["N-TAN-Tail-NoseBridge_1_1L"]: THREE.Bone;
    ["N-BB-Chin_2L"]: THREE.Bone;
    ["N-TAN-Cheek_1_4L"]: THREE.Bone;
    ["N-BB-ChinM"]: THREE.Bone;
    ["N-TAN-Tail-Cheek_1_4L"]: THREE.Bone;
    ["N-BB-LaughLineM"]: THREE.Bone;
    ["N-TAN-LaughLine_5L"]: THREE.Bone;
    ["N-BB-LaughLine_7L"]: THREE.Bone;
    ["N-TAN-LaughLine_4L"]: THREE.Bone;
    ["N-BB-LaughLine_6L"]: THREE.Bone;
    ["N-TAN-LaughLine_3L"]: THREE.Bone;
    ["N-BB-LaughLine_5L"]: THREE.Bone;
    ["N-TAN-LaughLine_2L"]: THREE.Bone;
    ["N-BB-LaughLine_4L"]: THREE.Bone;
    ["N-TAN-LaughLine_1L"]: THREE.Bone;
    ["N-TAN-Tail-LaughLine_1L"]: THREE.Bone;
    ["N-TAN-Lip_Bot_Bot_2L"]: THREE.Bone;
    ["N-TAN-Lip_Bot_Top_2L"]: THREE.Bone;
    ["N-TAN-Cheek_1_1L"]: THREE.Bone;
    ["N-BB-Cheek_1_1L"]: THREE.Bone;
    ["N-TAN-Cheek_1_2L"]: THREE.Bone;
    ["N-BB-Cheek_1_2L"]: THREE.Bone;
    ["N-TAN-Cheek_1_3L"]: THREE.Bone;
    ["N-TAN-Lip_Top_Top_1L"]: THREE.Bone;
    ["N-TAN-Tail-Lip_Top_Top_1L"]: THREE.Bone;
    ["N-TAN-Lip_Top_Bot_1L"]: THREE.Bone;
    ["N-TAN-Tail-Lip_Top_Bot_1L"]: THREE.Bone;
    ["N-TAN-LaughLine_Cheek_Across_1_1L"]: THREE.Bone;
    ["N-TAN-LaughLine_Cheek_Across_1_2L"]: THREE.Bone;
    ["N-TAN-LaughLine_Cheek_Across_2_1L"]: THREE.Bone;
    ["N-TAN-LaughLine_Cheek_Across_2_2L"]: THREE.Bone;
    ["N-TAN-Cheek_Cheek_Across_1L"]: THREE.Bone;
    ["N-TAN-Cheek_Cheek_Across_2L"]: THREE.Bone;
    ["N-TAN-Cheek_Jawline_AcrossL"]: THREE.Bone;
    ["N-TAN-Tail-Cheek_Jawline_AcrossL"]: THREE.Bone;
    ["N-BB-Lip_AboveM"]: THREE.Bone;
    ["N-TAN-NoseRing_1L"]: THREE.Bone;
    ["N-TAN-Nose_Lip_AcrossM"]: THREE.Bone;
    ["N-BB-Nostril_2L"]: THREE.Bone;
    ["N-TAN-NoseRing_2L"]: THREE.Bone;
    ["N-TAN-Tail-NoseMidLine_1L"]: THREE.Bone;
    ["N-TAN-Nose_Lip_AcrossL"]: THREE.Bone;
    ["N-BB-LaughLine_3R"]: THREE.Bone;
    ["N-TAN-NoseRing_3R"]: THREE.Bone;
    ["N-BB-LaughLine_2R"]: THREE.Bone;
    ["N-TAN-NoseRing_4R"]: THREE.Bone;
    ["N-BB-LaughLine_1R"]: THREE.Bone;
    ["N-TAN-NoseRing_5R"]: THREE.Bone;
    ["N-TAN-Tail-NoseRing_5R"]: THREE.Bone;
    ["N-TAN-NoseFront_1R"]: THREE.Bone;
    ["N-BB-Nostril_1R"]: THREE.Bone;
    ["N-TAN-NoseFront_2R"]: THREE.Bone;
    ["N-TAN-Tail-NoseFront_2R"]: THREE.Bone;
    ["N-BB-Forehead-_Top_1R"]: THREE.Bone;
    ["N-TAN-Forehead_2_2R"]: THREE.Bone;
    ["N-BB-Eyebrow_Top_1R"]: THREE.Bone;
    ["N-TAN-Eyebrow_Across_1R"]: THREE.Bone;
    ["N-BB-Eyebrow_Bot_1R"]: THREE.Bone;
    ["N-TAN-Brow_Crease_Across_2R"]: THREE.Bone;
    ["N-BB-EyeLid_Crease_2R"]: THREE.Bone;
    ["N-TAN-Crease_Lid_Across_2R"]: THREE.Bone;
    ["N-BB-Eyelid_Top_2R"]: THREE.Bone;
    ["N-TAN-Tail-Crease_Lid_Across_2R"]: THREE.Bone;
    ["N-BB-Forehead-_1R"]: THREE.Bone;
    ["N-TAN-Forehead_1_2R"]: THREE.Bone;
    ["N-BB-Eyebrow_1R"]: THREE.Bone;
    ["N-TAN-Brow_Crease_Across_1R"]: THREE.Bone;
    ["N-BB-EyeLid_Crease_1R"]: THREE.Bone;
    ["N-TAN-Crease_Lid_Across_1R"]: THREE.Bone;
    ["N-BB-Forehead-_Top_3R"]: THREE.Bone;
    ["N-TAN-Forehead_4_2R"]: THREE.Bone;
    ["N-BB-Eyebrow_Top_3R"]: THREE.Bone;
    ["N-TAN-Eyebrow_Across_3R"]: THREE.Bone;
    ["N-BB-Eyebrow_Bot_3R"]: THREE.Bone;
    ["N-TAN-FaceRing_1R"]: THREE.Bone;
    ["N-BB-NoseBridge_1R"]: THREE.Bone;
    ["N-TAN-FaceRing_2R"]: THREE.Bone;
    ["N-BB-NoseBridge_2R"]: THREE.Bone;
    ["N-TAN-FaceRing_3R"]: THREE.Bone;
    ["N-BB-Cheek_3_1R"]: THREE.Bone;
    ["N-TAN-FaceRing_6R"]: THREE.Bone;
    ["N-BB-Cheek_4_1R"]: THREE.Bone;
    ["N-TAN-FaceRing_7R"]: THREE.Bone;
    ["N-BB-Cheek_5_1R"]: THREE.Bone;
    ["N-TAN-FaceRing_8R"]: THREE.Bone;
    ["N-TAN-Eyebrow_Upper_1R"]: THREE.Bone;
    ["N-TAN-Eyebrow_Upper_2R"]: THREE.Bone;
    ["N-BB-Eyebrow_Top_2R"]: THREE.Bone;
    ["N-TAN-Eyebrow_Upper_3R"]: THREE.Bone;
    ["N-TAN-Eyebrow_Upper_4R"]: THREE.Bone;
    ["N-TAN-Tail-Eyebrow_Upper_4R"]: THREE.Bone;
    ["N-TAN-Brow_Crease_Across_4R"]: THREE.Bone;
    ["N-BB-EyeLid_Crease_4R"]: THREE.Bone;
    ["N-TAN-Crease_Lid_Across_4R"]: THREE.Bone;
    ["N-BB-Eyelid_Top_4R"]: THREE.Bone;
    ["N-TAN-Tail-Crease_Lid_Across_4R"]: THREE.Bone;
    ["N-BB-Forehead-_Top_2R"]: THREE.Bone;
    ["N-TAN-Forehead_3_2R"]: THREE.Bone;
    ["N-TAN-Eyebrow_Across_2R"]: THREE.Bone;
    ["N-BB-Eyebrow_Bot_2R"]: THREE.Bone;
    ["N-TAN-Brow_Crease_Across_3R"]: THREE.Bone;
    ["N-BB-EyeLid_Crease_3R"]: THREE.Bone;
    ["N-TAN-Crease_Lid_Across_3R"]: THREE.Bone;
    ["N-BB-Eyelid_Top_3R"]: THREE.Bone;
    ["N-TAN-Tail-Crease_Lid_Across_3R"]: THREE.Bone;
    ["N-BB-TempleR"]: THREE.Bone;
    ["N-TAN-Temple_2R"]: THREE.Bone;
    ["N-BB-JawLine_1R"]: THREE.Bone;
    ["N-TAN-JawLine_1R"]: THREE.Bone;
    ["N-BB-JawLine_2R"]: THREE.Bone;
    ["N-TAN-JawLine_2R"]: THREE.Bone;
    ["N-BB-JawLine_3R"]: THREE.Bone;
    ["N-TAN-JawLine_3R"]: THREE.Bone;
    ["N-BB-JawLine_4R"]: THREE.Bone;
    ["N-TAN-JawLine_4R"]: THREE.Bone;
    ["N-BB-JawLine_5R"]: THREE.Bone;
    ["N-TAN-JawLine_5R"]: THREE.Bone;
    ["N-TAN-Tail-JawLine_5R"]: THREE.Bone;
    ["N-TAN-Cheek_Jawline_Across_1R"]: THREE.Bone;
    ["N-TAN-Tail-Cheek_Jawline_Across_1R"]: THREE.Bone;
    ["N-TAN-Eyelid_Top_2R"]: THREE.Bone;
    ["N-TAN-Eyelid_Top_3R"]: THREE.Bone;
    ["N-TAN-Eyelid_Top_4R"]: THREE.Bone;
    ["N-BB-Eyelid_Top_5R"]: THREE.Bone;
    ["N-TAN-Tail-Eyelid_Top_4R"]: THREE.Bone;
    ["N-BB-Eyelid_Bot_2R"]: THREE.Bone;
    ["N-TAN-Eyelid_Bot_2R"]: THREE.Bone;
    ["N-BB-Eyelid_Bot_3R"]: THREE.Bone;
    ["N-TAN-Eyelid_Bot_3R"]: THREE.Bone;
    ["N-BB-Eyelid_Bot_4R"]: THREE.Bone;
    ["N-TAN-Eyelid_Bot_4R"]: THREE.Bone;
    ["N-BB-EyeLid_Crease_5R"]: THREE.Bone;
    ["N-TAN-NoseBridge_2_2R"]: THREE.Bone;
    ["N-TAN-NoseBridge_2_3R"]: THREE.Bone;
    ["N-TAN-Tail-NoseBridge_2_3R"]: THREE.Bone;
    ["N-TAN-NoseMidLine_3R"]: THREE.Bone;
    ["N-TAN-NoseMidLine_2R"]: THREE.Bone;
    ["N-TAN-NoseMidLine_1R"]: THREE.Bone;
    ["N-BB-Lip_Top_TopR"]: THREE.Bone;
    ["N-TAN-Lip_Top_AcrossR"]: THREE.Bone;
    ["N-BB-Lip_Top_BotR"]: THREE.Bone;
    ["N-TAN-Tail-Lip_Top_AcrossR"]: THREE.Bone;
    ["N-TAN-Cheek_2_0R"]: THREE.Bone;
    ["N-BB-Cheek_2_2R"]: THREE.Bone;
    ["N-TAN-Cheek_2_3R"]: THREE.Bone;
    ["N-TAN-Tail-Cheek_2_3R"]: THREE.Bone;
    ["N-TAN-NoseCrease_0R"]: THREE.Bone;
    ["N-TAN-Tail-NoseCrease_2R"]: THREE.Bone;
    ["N-TAN-Cheek_3_0R"]: THREE.Bone;
    ["N-BB-EyeLid_Crease_8R"]: THREE.Bone;
    ["N-TAN-Cheek_3_1R"]: THREE.Bone;
    ["N-TAN-Cheek_3_2R"]: THREE.Bone;
    ["N-BB-Cheek_3_2R"]: THREE.Bone;
    ["N-TAN-Cheek_Jawline_Across_3R"]: THREE.Bone;
    ["N-TAN-Tail-Cheek_Jawline_Across_3R"]: THREE.Bone;
    ["N-BB-EyeLid_Crease_10R"]: THREE.Bone;
    ["N-TAN-Cheek_5_1R"]: THREE.Bone;
    ["N-TAN-Cheek_5_2R"]: THREE.Bone;
    ["N-TAN-Tail-Cheek_5_2R"]: THREE.Bone;
    ["N-TAN-Cheek_4_2R"]: THREE.Bone;
    ["N-BB-Cheek_4_2R"]: THREE.Bone;
    ["N-TAN-Cheek_4_3R"]: THREE.Bone;
    ["N-TAN-Tail-Cheek_4_3R"]: THREE.Bone;
    ["N-TAN-Eyebrow_Lower_1R"]: THREE.Bone;
    ["N-TAN-Eyebrow_Lower_2R"]: THREE.Bone;
    ["N-TAN-Eyebrow_Lower_3R"]: THREE.Bone;
    ["N-TAN-Eyebrow_Lower_4R"]: THREE.Bone;
    ["N-TAN-Tail-Eyebrow_Lower_4R"]: THREE.Bone;
    ["N-BB-Lip_Bot_BotR"]: THREE.Bone;
    ["N-TAN-Lip_Bot_AcrossR"]: THREE.Bone;
    ["N-BB-Lip_Bot_TopR"]: THREE.Bone;
    ["N-TAN-Tail-Lip_Bot_AcrossR"]: THREE.Bone;
    ["N-TAN-EyeLid_Crease_4R"]: THREE.Bone;
    ["N-TAN-EyeLid_Crease_5R"]: THREE.Bone;
    ["N-TAN-EyeLid_Crease_8R"]: THREE.Bone;
    ["N-TAN-EyeLid_Crease_10R"]: THREE.Bone;
    ["N-TAN-EyeLid_Crease_1R"]: THREE.Bone;
    ["N-TAN-EyeLid_Crease_2R"]: THREE.Bone;
    ["N-TAN-EyeLid_Crease_3R"]: THREE.Bone;
    ["N-TAN-NoseBridge_1_2R"]: THREE.Bone;
    ["N-TAN-NoseBridge_1_1R"]: THREE.Bone;
    ["N-TAN-Tail-NoseBridge_1_1R"]: THREE.Bone;
    ["N-BB-Chin_2R"]: THREE.Bone;
    ["N-TAN-Cheek_1_4R"]: THREE.Bone;
    ["N-TAN-Tail-Cheek_1_4R"]: THREE.Bone;
    ["N-TAN-LaughLine_5R"]: THREE.Bone;
    ["N-BB-LaughLine_7R"]: THREE.Bone;
    ["N-TAN-LaughLine_4R"]: THREE.Bone;
    ["N-BB-LaughLine_6R"]: THREE.Bone;
    ["N-TAN-LaughLine_3R"]: THREE.Bone;
    ["N-BB-LaughLine_5R"]: THREE.Bone;
    ["N-TAN-LaughLine_2R"]: THREE.Bone;
    ["N-BB-LaughLine_4R"]: THREE.Bone;
    ["N-TAN-LaughLine_1R"]: THREE.Bone;
    ["N-TAN-Tail-LaughLine_1R"]: THREE.Bone;
    ["N-TAN-Lip_Bot_Bot_2R"]: THREE.Bone;
    ["N-TAN-Lip_Bot_Top_2R"]: THREE.Bone;
    ["N-TAN-Cheek_1_1R"]: THREE.Bone;
    ["N-BB-Cheek_1_1R"]: THREE.Bone;
    ["N-TAN-Cheek_1_2R"]: THREE.Bone;
    ["N-BB-Cheek_1_2R"]: THREE.Bone;
    ["N-TAN-Cheek_1_3R"]: THREE.Bone;
    ["N-TAN-Lip_Top_Top_1R"]: THREE.Bone;
    ["N-TAN-Tail-Lip_Top_Top_1R"]: THREE.Bone;
    ["N-TAN-Lip_Top_Bot_1R"]: THREE.Bone;
    ["N-TAN-Tail-Lip_Top_Bot_1R"]: THREE.Bone;
    ["N-TAN-LaughLine_Cheek_Across_1_1R"]: THREE.Bone;
    ["N-TAN-LaughLine_Cheek_Across_1_2R"]: THREE.Bone;
    ["N-TAN-LaughLine_Cheek_Across_2_1R"]: THREE.Bone;
    ["N-TAN-LaughLine_Cheek_Across_2_2R"]: THREE.Bone;
    ["N-TAN-Cheek_Cheek_Across_1R"]: THREE.Bone;
    ["N-TAN-Cheek_Cheek_Across_2R"]: THREE.Bone;
    ["N-TAN-Cheek_Jawline_AcrossR"]: THREE.Bone;
    ["N-TAN-Tail-Cheek_Jawline_AcrossR"]: THREE.Bone;
    ["N-TAN-NoseRing_1R"]: THREE.Bone;
    ["N-BB-Nostril_2R"]: THREE.Bone;
    ["N-TAN-NoseRing_2R"]: THREE.Bone;
    ["N-TAN-Tail-NoseMidLine_1R"]: THREE.Bone;
    ["N-TAN-Nose_Lip_AcrossR"]: THREE.Bone;
    ["IK-P-Pole-ForearmL"]: THREE.Bone;
    ["IK-P-Hand_ParentL"]: THREE.Bone;
    ["MSTR-P-Foot_ParentL"]: THREE.Bone;
    ["IK-P-Pole-ForearmR"]: THREE.Bone;
    ["IK-P-Hand_ParentR"]: THREE.Bone;
    ["MSTR-P-Foot_ParentR"]: THREE.Bone;
  };
  materials: {
    ["MAT-rain.body"]: THREE.MeshStandardMaterial;
    ["MAT-rain.hands"]: THREE.MeshStandardMaterial;
    ["MAT-rain.jeans"]: THREE.MeshStandardMaterial;
    ["MAT-rain.top"]: THREE.MeshStandardMaterial;
    ["MAT-rain.cornea"]: THREE.MeshStandardMaterial;
    ["MAT-rain.eyebrows"]: THREE.MeshStandardMaterial;
    ["MAT-rain.eyelashes"]: THREE.MeshStandardMaterial;
    ["MAT-rain.gums"]: THREE.MeshStandardMaterial;
    ["MAT-rain.teeth"]: THREE.MeshStandardMaterial;
    ["MAT-rain.hair"]: THREE.MeshStandardMaterial;
    ["MAT-rain.hairband"]: THREE.MeshStandardMaterial;
    ["MAT-rain.head"]: THREE.MeshStandardMaterial;
    ["MAT-rain.shoes"]: THREE.MeshStandardMaterial;
    ["MAT-rain.metal"]: THREE.MeshStandardMaterial;
    ["MAT-rain.socks"]: THREE.MeshStandardMaterial;
    ["MAT-rain.laces"]: THREE.MeshStandardMaterial;
    ["MAT-rain.eyes"]: THREE.MeshStandardMaterial;
    ["MAT-rain.hair"]: THREE.MeshStandardMaterial;
    ["MAT-rain.tongue"]: THREE.MeshStandardMaterial;
    ["Material.003"]: THREE.MeshStandardMaterial;
    ["Material.004"]: THREE.MeshStandardMaterial;
  };
  animations: GLTFActions[];
};

interface CharacterProps {
  action: number;
}

export default function Character(props: CharacterProps) {
  const group = useRef<THREE.Group | null>(null);
  const { nodes, materials, animations } = useGLTF(
    "/rain_rig.glb"
  ) as unknown as GLTFResult;
  const { actions, mixer } = useAnimations(animations, group);
  const { scene } = useThree();
  useEffect(() => {
    // if(!actions.all) return
    // actions.all.play()
    materials["MAT-rain.eyebrows"].emissiveIntensity = 0;
    materials["MAT-rain.body"].emissiveIntensity = 0;
    materials["MAT-rain.hands"].emissiveIntensity = 0;
    materials["MAT-rain.jeans"].emissiveIntensity = 0;
    materials["MAT-rain.top"].emissiveIntensity = 0;
    materials["MAT-rain.eyebrows"].emissiveIntensity = 0;
    materials["MAT-rain.eyelashes"].emissiveIntensity = 0;
    materials["MAT-rain.gums"].emissiveIntensity = 0;
    materials["MAT-rain.teeth"].emissiveIntensity = 0;
    materials["MAT-rain.hair"].emissiveIntensity = 0;
    materials["MAT-rain.hairband"].emissiveIntensity = 0;
    materials["MAT-rain.head"].emissiveIntensity = 0;
    materials["MAT-rain.shoes"].emissiveIntensity = 0;
    materials["MAT-rain.metal"].emissiveIntensity = 0;
    materials["MAT-rain.socks"].emissiveIntensity = 0;
    materials["MAT-rain.laces"].emissiveIntensity = 0;
    materials["MAT-rain.eyes"].emissiveIntensity = 0;
    materials["MAT-rain.hair"].emissiveIntensity = 0;
    materials["MAT-rain.tongue"].emissiveIntensity = 0;
    materials["Material.003"].emissiveIntensity = 0;
    materials["Material.004"].toneMapped = false;
    console.log(materials["MAT-rain.body"].toneMapped);
  }, []);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="RIG-rain">
          <primitive object={nodes.TeethT} />
          <primitive object={nodes.TeethB} />
          <primitive object={nodes["P-BB-ChinM"]} />
          <primitive object={nodes["P-GRP-Lip_TopM"]} />
          <primitive object={nodes["P-BB-Chin_2L"]} />
          <primitive object={nodes["P-BB-LaughLineM"]} />
          <primitive object={nodes["P-BB-LaughLine_7L"]} />
          <primitive object={nodes["P-GRP-Lip_BotM"]} />
          <primitive object={nodes["FK-ToeL"]} />
          <primitive object={nodes["DEF-COR-Shin_TopL"]} />
          <primitive object={nodes["GRAB-HandL"]} />
          <primitive object={nodes["P-BB-JawLine_3L"]} />
          <primitive object={nodes["P-BB-Nose_3M"]} />
          <primitive object={nodes["P-BB-Cheek_SneerL"]} />
          <primitive object={nodes["P-BB-Cheek_3_2L"]} />
          <primitive object={nodes["P-BB-Cheek_2_2L"]} />
          <primitive object={nodes["P-BB-LaughLine_2L"]} />
          <primitive object={nodes["P-BB-Nostril_2L"]} />
          <primitive object={nodes["P-BB-Nostril_1L"]} />
          <primitive object={nodes["P-BB-LaughLine_1L"]} />
          <primitive object={nodes["P-BB-LaughLine_6L"]} />
          <primitive object={nodes["P-BB-LaughLine_4L"]} />
          <primitive object={nodes["P-BB-Cheek_2_1L"]} />
          <primitive object={nodes["P-BB-Cheek_3_1L"]} />
          <primitive object={nodes["P-BB-JawLine_2L"]} />
          <primitive object={nodes["P-BB-LaughLine_5L"]} />
          <primitive object={nodes["P-BB-Cheek_1_2L"]} />
          <primitive object={nodes["P-BB-Cheek_4_2L"]} />
          <primitive object={nodes["P-BB-Cheek_1_1L"]} />
          <primitive object={nodes["P-GRP-Nose_Front"]} />
          <primitive object={nodes["P-GRP-Lip_Top_1L"]} />
          <primitive object={nodes["P-GRP-Lip_Bot_1L"]} />
          <primitive object={nodes.Tongue_Root} />
          <primitive object={nodes["N-BB-Eyelid_Top_1L"]} />
          <primitive object={nodes["N-TAN-Tail-Crease_Lid_Across_1L"]} />
          <primitive object={nodes["N-BB-Cheek_SneerL"]} />
          <primitive object={nodes["N-TAN-FaceRing_4L"]} />
          <primitive object={nodes["N-BB-Cheek_2_1L"]} />
          <primitive object={nodes["N-TAN-FaceRing_5L"]} />
          <primitive object={nodes["N-BB-Eyelid_Bot_5L"]} />
          <primitive object={nodes["N-TAN-Cheek_4_0L"]} />
          <primitive object={nodes["N-BB-EyeLid_Crease_9L"]} />
          <primitive object={nodes["N-TAN-Cheek_4_1L"]} />
          <primitive object={nodes["N-TAN-Eyelid_Top_1L"]} />
          <primitive object={nodes["N-BB-Eyelid_Bot_1L"]} />
          <primitive object={nodes["N-TAN-Eyelid_Bot_1L"]} />
          <primitive object={nodes["N-TAN-Tail-Eyelid_Bot_4L"]} />
          <primitive object={nodes["N-BB-EyeLid_Crease_7L"]} />
          <primitive object={nodes["N-TAN-Cheek_2_1L"]} />
          <primitive object={nodes["N-TAN-Cheek_2_2L"]} />
          <primitive object={nodes["N-TAN-NoseCrease_2L"]} />
          <primitive object={nodes["N-TAN-EyeLid_Crease_7L"]} />
          <primitive object={nodes["N-TAN-EyeLid_Crease_9L"]} />
          <primitive object={nodes["N-BB-Lip_Bot_BotM"]} />
          <primitive object={nodes["N-TAN-Lip_Bot_Bot_1L"]} />
          <primitive object={nodes["N-BB-Lip_Bot_CornerL"]} />
          <primitive object={nodes["N-TAN-Tail-Lip_Bot_Bot_2L"]} />
          <primitive object={nodes["N-TAN-Lip_Bot_AcrossM"]} />
          <primitive object={nodes["N-BB-Lip_Bot_TopM"]} />
          <primitive object={nodes["N-TAN-Tail-Lip_Bot_AcrossM"]} />
          <primitive object={nodes["N-TAN-Lip_Bot_Top_1L"]} />
          <primitive object={nodes["N-TAN-Tail-Lip_Bot_Top_2L"]} />
          <primitive object={nodes["N-BB-Lip_Top_CornerL"]} />
          <primitive object={nodes["N-TAN-Lip_Top_Top_2L"]} />
          <primitive object={nodes["N-TAN-Lip_Top_Bot_2L"]} />
          <primitive object={nodes["N-TAN-LaughLine_Lip_Across_1L"]} />
          <primitive object={nodes["N-TAN-Tail-LaughLine_Cheek_Across_1_2L"]} />
          <primitive object={nodes["N-TAN-LaughLine_Lip_Across_2L"]} />
          <primitive object={nodes.ROOT} />
          <primitive object={nodes["HNG-ThighL"]} />
          <primitive object={nodes["HNG-Upperarm_ParentL"]} />
          <primitive object={nodes["CTR-COR-Thumb_1L"]} />
          <primitive object={nodes["TGT-Eyes"]} />
          <primitive object={nodes["P-FK-Head"]} />
          <primitive object={nodes["P-GRP-Lip_Bot_2L"]} />
          <primitive object={nodes["P-GRP-Lip_Bot_2R"]} />
          <primitive object={nodes["P-GRP-Lip_Top_2L"]} />
          <primitive object={nodes["P-GRP-Lip_Top_2R"]} />
          <primitive object={nodes["P-ACT-Lips_CornerL"]} />
          <primitive object={nodes["P-ACT-Lips_CornerR"]} />
          <primitive object={nodes["P-BB-Cheek_4_1L"]} />
          <primitive object={nodes["P-BB-JawLine_1L"]} />
          <primitive object={nodes["P-GRP-NostrilL"]} />
          <primitive object={nodes["P-BB-Forehead-_TopM"]} />
          <primitive object={nodes["GRP-Nose_Bridge2"]} />
          <primitive object={nodes["P-BB-Forehead-_Top_1L"]} />
          <primitive object={nodes["P-BB-Forehead-_Top_3L"]} />
          <primitive object={nodes["P-BB-Forehead-_Top_2L"]} />
          <primitive object={nodes["P-BB-Forehead-_1L"]} />
          <primitive object={nodes["P-FK-Neck"]} />
          <primitive object={nodes["P-BB-Chin_2R"]} />
          <primitive object={nodes["P-BB-LaughLine_7R"]} />
          <primitive object={nodes["P-BB-JawLine_3R"]} />
          <primitive object={nodes["P-BB-Cheek_SneerR"]} />
          <primitive object={nodes["P-BB-Cheek_3_2R"]} />
          <primitive object={nodes["P-BB-Cheek_2_2R"]} />
          <primitive object={nodes["P-BB-LaughLine_2R"]} />
          <primitive object={nodes["P-BB-Nostril_2R"]} />
          <primitive object={nodes["P-BB-Nostril_1R"]} />
          <primitive object={nodes["P-BB-LaughLine_1R"]} />
          <primitive object={nodes["P-BB-LaughLine_6R"]} />
          <primitive object={nodes["P-BB-LaughLine_4R"]} />
          <primitive object={nodes["P-BB-Cheek_2_1R"]} />
          <primitive object={nodes["P-BB-Cheek_3_1R"]} />
          <primitive object={nodes["P-BB-JawLine_2R"]} />
          <primitive object={nodes["P-BB-LaughLine_5R"]} />
          <primitive object={nodes["P-BB-Cheek_1_2R"]} />
          <primitive object={nodes["P-BB-Cheek_4_2R"]} />
          <primitive object={nodes["P-BB-Cheek_1_1R"]} />
          <primitive object={nodes["P-GRP-Lip_Top_1R"]} />
          <primitive object={nodes["P-GRP-Lip_Bot_1R"]} />
          <primitive object={nodes["N-BB-Eyelid_Top_1R"]} />
          <primitive object={nodes["N-TAN-Tail-Crease_Lid_Across_1R"]} />
          <primitive object={nodes["N-BB-Cheek_SneerR"]} />
          <primitive object={nodes["N-TAN-FaceRing_4R"]} />
          <primitive object={nodes["N-BB-Cheek_2_1R"]} />
          <primitive object={nodes["N-TAN-FaceRing_5R"]} />
          <primitive object={nodes["N-BB-Eyelid_Bot_5R"]} />
          <primitive object={nodes["N-TAN-Cheek_4_0R"]} />
          <primitive object={nodes["N-BB-EyeLid_Crease_9R"]} />
          <primitive object={nodes["N-TAN-Cheek_4_1R"]} />
          <primitive object={nodes["N-TAN-Eyelid_Top_1R"]} />
          <primitive object={nodes["N-BB-Eyelid_Bot_1R"]} />
          <primitive object={nodes["N-TAN-Eyelid_Bot_1R"]} />
          <primitive object={nodes["N-TAN-Tail-Eyelid_Bot_4R"]} />
          <primitive object={nodes["N-BB-EyeLid_Crease_7R"]} />
          <primitive object={nodes["N-TAN-Cheek_2_1R"]} />
          <primitive object={nodes["N-TAN-Cheek_2_2R"]} />
          <primitive object={nodes["N-BB-EyeLid_Crease_6R"]} />
          <primitive object={nodes["N-TAN-NoseCrease_1R"]} />
          <primitive object={nodes["N-TAN-NoseCrease_2R"]} />
          <primitive object={nodes["N-TAN-EyeLid_Crease_6R"]} />
          <primitive object={nodes["N-TAN-EyeLid_Crease_7R"]} />
          <primitive object={nodes["N-TAN-EyeLid_Crease_9R"]} />
          <primitive object={nodes["N-TAN-Lip_Bot_Bot_1R"]} />
          <primitive object={nodes["N-BB-Lip_Bot_CornerR"]} />
          <primitive object={nodes["N-TAN-Tail-Lip_Bot_Bot_2R"]} />
          <primitive object={nodes["N-TAN-Lip_Bot_Top_1R"]} />
          <primitive object={nodes["N-TAN-Tail-Lip_Bot_Top_2R"]} />
          <primitive object={nodes["N-BB-Lip_Top_CornerR"]} />
          <primitive object={nodes["N-TAN-Lip_Top_Top_2R"]} />
          <primitive object={nodes["N-TAN-Lip_Top_Bot_2R"]} />
          <primitive object={nodes["N-TAN-LaughLine_Lip_Across_1R"]} />
          <primitive object={nodes["N-TAN-Tail-LaughLine_Cheek_Across_1_2R"]} />
          <primitive object={nodes["N-TAN-LaughLine_Lip_Across_2R"]} />
          <primitive object={nodes["P-BB-Cheek_4_1R"]} />
          <primitive object={nodes["P-BB-JawLine_1R"]} />
          <primitive object={nodes["P-GRP-NostrilR"]} />
          <primitive object={nodes["P-BB-Forehead-_Top_1R"]} />
          <primitive object={nodes["P-BB-Forehead-_Top_3R"]} />
          <primitive object={nodes["P-BB-Forehead-_Top_2R"]} />
          <primitive object={nodes["P-BB-Forehead-_1R"]} />
          <primitive object={nodes["P-GRP-Nose_Bridge"]} />
          <primitive object={nodes["CTR-COR-Thumb_2L"]} />
          <primitive object={nodes["GRP-STR-Nose_Front"]} />
          <primitive object={nodes["GRP-STR-NostrilL"]} />
          <primitive object={nodes["GRP-STR-NostrilR"]} />
          <primitive object={nodes["P-SK-Cheek_PuffL"]} />
          <primitive object={nodes["P-SK-Cheek_PuffR"]} />
          <primitive object={nodes["FK-ToeR"]} />
          <primitive object={nodes["DEF-COR-Shin_TopR"]} />
          <primitive object={nodes["GRAB-HandR"]} />
          <primitive object={nodes["HNG-ThighR"]} />
          <primitive object={nodes["HNG-Upperarm_ParentR"]} />
          <primitive object={nodes["CTR-COR-Thumb_1R"]} />
          <primitive object={nodes["CTR-COR-Thumb_2R"]} />
          <primitive object={nodes.Root_EarL} />
          <primitive object={nodes.Root_EarR} />
          <primitive object={nodes["IK-P-Pole-ShinL"]} />
          <primitive object={nodes["IK-P-Pole-ShinR"]} />
          <primitive object={nodes["N-BB-Forehead-_TopM"]} />
          <primitive object={nodes["N-TAN-Forehead_2M"]} />
          <primitive object={nodes["N-BB-Eyebrow_TopM"]} />
          <primitive object={nodes["N-TAN-Eyebrow_AcrossM"]} />
          <primitive object={nodes["N-BB-Eyebrow_BotM"]} />
          <primitive object={nodes["N-TAN-Nose_1M"]} />
          <primitive object={nodes["N-BB-Nose_1M"]} />
          <primitive object={nodes["N-TAN-Nose_2M"]} />
          <primitive object={nodes["N-BB-Nose_2M"]} />
          <primitive object={nodes["N-TAN-Nose_3M"]} />
          <primitive object={nodes["N-BB-Nose_3M"]} />
          <primitive object={nodes["N-TAN-Nose_4M"]} />
          <primitive object={nodes["N-BB-Nose_4M"]} />
          <primitive object={nodes["N-TAN-Nose_5M"]} />
          <primitive object={nodes["N-BB-Lip_Top_TopM"]} />
          <primitive object={nodes["N-TAN-Lip_Top_AcrossM"]} />
          <primitive object={nodes["N-BB-Lip_Top_BotM"]} />
          <primitive object={nodes["N-TAN-Tail-Lip_Top_AcrossM"]} />
          <primitive object={nodes["N-BB-LaughLine_3L"]} />
          <primitive object={nodes["N-TAN-NoseRing_3L"]} />
          <primitive object={nodes["N-BB-LaughLine_2L"]} />
          <primitive object={nodes["N-TAN-NoseRing_4L"]} />
          <primitive object={nodes["N-BB-LaughLine_1L"]} />
          <primitive object={nodes["N-TAN-NoseRing_5L"]} />
          <primitive object={nodes["N-TAN-Tail-NoseRing_5L"]} />
          <primitive object={nodes["N-TAN-NoseFront_1L"]} />
          <primitive object={nodes["N-BB-Nostril_1L"]} />
          <primitive object={nodes["N-TAN-NoseFront_2L"]} />
          <primitive object={nodes["N-TAN-Tail-NoseFront_2L"]} />
          <primitive object={nodes["N-BB-Forehead-_Top_1L"]} />
          <primitive object={nodes["N-TAN-Forehead_2_2L"]} />
          <primitive object={nodes["N-BB-Eyebrow_Top_1L"]} />
          <primitive object={nodes["N-TAN-Eyebrow_Across_1L"]} />
          <primitive object={nodes["N-BB-Eyebrow_Bot_1L"]} />
          <primitive object={nodes["N-TAN-Brow_Crease_Across_2L"]} />
          <primitive object={nodes["N-BB-EyeLid_Crease_2L"]} />
          <primitive object={nodes["N-TAN-Crease_Lid_Across_2L"]} />
          <primitive object={nodes["N-BB-Eyelid_Top_2L"]} />
          <primitive object={nodes["N-TAN-Tail-Crease_Lid_Across_2L"]} />
          <primitive object={nodes["N-BB-Forehead-_1L"]} />
          <primitive object={nodes["N-TAN-Forehead_1_2L"]} />
          <primitive object={nodes["N-BB-Eyebrow_1L"]} />
          <primitive object={nodes["N-TAN-Brow_Crease_Across_1L"]} />
          <primitive object={nodes["N-BB-EyeLid_Crease_1L"]} />
          <primitive object={nodes["N-TAN-Crease_Lid_Across_1L"]} />
          <primitive object={nodes["N-BB-Forehead-_Top_3L"]} />
          <primitive object={nodes["N-TAN-Forehead_4_2L"]} />
          <primitive object={nodes["N-BB-Eyebrow_Top_3L"]} />
          <primitive object={nodes["N-TAN-Eyebrow_Across_3L"]} />
          <primitive object={nodes["N-BB-Eyebrow_Bot_3L"]} />
          <primitive object={nodes["N-TAN-FaceRing_1L"]} />
          <primitive object={nodes["N-BB-NoseBridge_1L"]} />
          <primitive object={nodes["N-TAN-FaceRing_2L"]} />
          <primitive object={nodes["N-BB-NoseBridge_2L"]} />
          <primitive object={nodes["N-TAN-FaceRing_3L"]} />
          <primitive object={nodes["N-BB-Cheek_3_1L"]} />
          <primitive object={nodes["N-TAN-FaceRing_6L"]} />
          <primitive object={nodes["N-BB-Cheek_4_1L"]} />
          <primitive object={nodes["N-TAN-FaceRing_7L"]} />
          <primitive object={nodes["N-BB-Cheek_5_1L"]} />
          <primitive object={nodes["N-TAN-FaceRing_8L"]} />
          <primitive object={nodes["N-TAN-Eyebrow_Upper_1L"]} />
          <primitive object={nodes["N-TAN-Eyebrow_Upper_2L"]} />
          <primitive object={nodes["N-BB-Eyebrow_Top_2L"]} />
          <primitive object={nodes["N-TAN-Eyebrow_Upper_3L"]} />
          <primitive object={nodes["N-TAN-Eyebrow_Upper_4L"]} />
          <primitive object={nodes["N-TAN-Tail-Eyebrow_Upper_4L"]} />
          <primitive object={nodes["N-TAN-Brow_Crease_Across_4L"]} />
          <primitive object={nodes["N-BB-EyeLid_Crease_4L"]} />
          <primitive object={nodes["N-TAN-Crease_Lid_Across_4L"]} />
          <primitive object={nodes["N-BB-Eyelid_Top_4L"]} />
          <primitive object={nodes["N-TAN-Tail-Crease_Lid_Across_4L"]} />
          <primitive object={nodes["N-BB-Forehead-_Top_2L"]} />
          <primitive object={nodes["N-TAN-Forehead_3_2L"]} />
          <primitive object={nodes["N-TAN-Eyebrow_Across_2L"]} />
          <primitive object={nodes["N-BB-Eyebrow_Bot_2L"]} />
          <primitive object={nodes["N-TAN-Brow_Crease_Across_3L"]} />
          <primitive object={nodes["N-BB-EyeLid_Crease_3L"]} />
          <primitive object={nodes["N-TAN-Crease_Lid_Across_3L"]} />
          <primitive object={nodes["N-BB-Eyelid_Top_3L"]} />
          <primitive object={nodes["N-TAN-Tail-Crease_Lid_Across_3L"]} />
          <primitive object={nodes["N-BB-TempleL"]} />
          <primitive object={nodes["N-TAN-Temple_2L"]} />
          <primitive object={nodes["N-BB-JawLine_1L"]} />
          <primitive object={nodes["N-TAN-JawLine_1L"]} />
          <primitive object={nodes["N-BB-JawLine_2L"]} />
          <primitive object={nodes["N-TAN-JawLine_2L"]} />
          <primitive object={nodes["N-BB-JawLine_3L"]} />
          <primitive object={nodes["N-TAN-JawLine_3L"]} />
          <primitive object={nodes["N-BB-JawLine_4L"]} />
          <primitive object={nodes["N-TAN-JawLine_4L"]} />
          <primitive object={nodes["N-BB-JawLine_5L"]} />
          <primitive object={nodes["N-TAN-JawLine_5L"]} />
          <primitive object={nodes["N-BB-JawLineM"]} />
          <primitive object={nodes["N-TAN-Tail-JawLine_5L"]} />
          <primitive object={nodes["N-TAN-Cheek_Jawline_Across_1L"]} />
          <primitive object={nodes["N-TAN-Tail-Cheek_Jawline_Across_1L"]} />
          <primitive object={nodes["N-TAN-Eyelid_Top_2L"]} />
          <primitive object={nodes["N-TAN-Eyelid_Top_3L"]} />
          <primitive object={nodes["N-TAN-Eyelid_Top_4L"]} />
          <primitive object={nodes["N-BB-Eyelid_Top_5L"]} />
          <primitive object={nodes["N-TAN-Tail-Eyelid_Top_4L"]} />
          <primitive object={nodes["N-BB-Eyelid_Bot_2L"]} />
          <primitive object={nodes["N-TAN-Eyelid_Bot_2L"]} />
          <primitive object={nodes["N-BB-Eyelid_Bot_3L"]} />
          <primitive object={nodes["N-TAN-Eyelid_Bot_3L"]} />
          <primitive object={nodes["N-BB-Eyelid_Bot_4L"]} />
          <primitive object={nodes["N-TAN-Eyelid_Bot_4L"]} />
          <primitive object={nodes["N-BB-EyeLid_Crease_5L"]} />
          <primitive object={nodes["N-TAN-NoseBridge_2_2L"]} />
          <primitive object={nodes["N-TAN-NoseBridge_2_3L"]} />
          <primitive object={nodes["N-TAN-Tail-NoseBridge_2_3L"]} />
          <primitive object={nodes["N-TAN-NoseMidLine_3L"]} />
          <primitive object={nodes["N-TAN-NoseMidLine_2L"]} />
          <primitive object={nodes["N-TAN-NoseMidLine_1L"]} />
          <primitive object={nodes["N-BB-Lip_Top_TopL"]} />
          <primitive object={nodes["N-TAN-Lip_Top_AcrossL"]} />
          <primitive object={nodes["N-BB-Lip_Top_BotL"]} />
          <primitive object={nodes["N-TAN-Tail-Lip_Top_AcrossL"]} />
          <primitive object={nodes["N-TAN-Cheek_2_0L"]} />
          <primitive object={nodes["N-BB-Cheek_2_2L"]} />
          <primitive object={nodes["N-TAN-Cheek_2_3L"]} />
          <primitive object={nodes["N-TAN-Tail-Cheek_2_3L"]} />
          <primitive object={nodes["N-TAN-NoseCrease_0L"]} />
          <primitive object={nodes["N-BB-EyeLid_Crease_6L"]} />
          <primitive object={nodes["N-TAN-NoseCrease_1L"]} />
          <primitive object={nodes["N-TAN-Tail-NoseCrease_2L"]} />
          <primitive object={nodes["N-TAN-Cheek_3_0L"]} />
          <primitive object={nodes["N-BB-EyeLid_Crease_8L"]} />
          <primitive object={nodes["N-TAN-Cheek_3_1L"]} />
          <primitive object={nodes["N-TAN-Cheek_3_2L"]} />
          <primitive object={nodes["N-BB-Cheek_3_2L"]} />
          <primitive object={nodes["N-TAN-Cheek_Jawline_Across_3L"]} />
          <primitive object={nodes["N-TAN-Tail-Cheek_Jawline_Across_3L"]} />
          <primitive object={nodes["N-BB-EyeLid_Crease_10L"]} />
          <primitive object={nodes["N-TAN-Cheek_5_1L"]} />
          <primitive object={nodes["N-TAN-Cheek_5_2L"]} />
          <primitive object={nodes["N-TAN-Tail-Cheek_5_2L"]} />
          <primitive object={nodes["N-TAN-Cheek_4_2L"]} />
          <primitive object={nodes["N-BB-Cheek_4_2L"]} />
          <primitive object={nodes["N-TAN-Cheek_4_3L"]} />
          <primitive object={nodes["N-TAN-Tail-Cheek_4_3L"]} />
          <primitive object={nodes["N-TAN-Eyebrow_Lower_1L"]} />
          <primitive object={nodes["N-TAN-Eyebrow_Lower_2L"]} />
          <primitive object={nodes["N-TAN-Eyebrow_Lower_3L"]} />
          <primitive object={nodes["N-TAN-Eyebrow_Lower_4L"]} />
          <primitive object={nodes["N-TAN-Tail-Eyebrow_Lower_4L"]} />
          <primitive object={nodes["N-BB-Lip_Bot_BotL"]} />
          <primitive object={nodes["N-TAN-Lip_Bot_AcrossL"]} />
          <primitive object={nodes["N-BB-Lip_Bot_TopL"]} />
          <primitive object={nodes["N-TAN-Tail-Lip_Bot_AcrossL"]} />
          <primitive object={nodes["N-TAN-EyeLid_Crease_4L"]} />
          <primitive object={nodes["N-TAN-EyeLid_Crease_5L"]} />
          <primitive object={nodes["N-TAN-EyeLid_Crease_6L"]} />
          <primitive object={nodes["N-TAN-EyeLid_Crease_8L"]} />
          <primitive object={nodes["N-TAN-EyeLid_Crease_10L"]} />
          <primitive object={nodes["N-TAN-EyeLid_Crease_1L"]} />
          <primitive object={nodes["N-TAN-EyeLid_Crease_2L"]} />
          <primitive object={nodes["N-TAN-EyeLid_Crease_3L"]} />
          <primitive object={nodes["N-TAN-NoseBridge_1_2L"]} />
          <primitive object={nodes["N-TAN-NoseBridge_1_1L"]} />
          <primitive object={nodes["N-TAN-Tail-NoseBridge_1_1L"]} />
          <primitive object={nodes["N-BB-Chin_2L"]} />
          <primitive object={nodes["N-TAN-Cheek_1_4L"]} />
          <primitive object={nodes["N-BB-ChinM"]} />
          <primitive object={nodes["N-TAN-Tail-Cheek_1_4L"]} />
          <primitive object={nodes["N-BB-LaughLineM"]} />
          <primitive object={nodes["N-TAN-LaughLine_5L"]} />
          <primitive object={nodes["N-BB-LaughLine_7L"]} />
          <primitive object={nodes["N-TAN-LaughLine_4L"]} />
          <primitive object={nodes["N-BB-LaughLine_6L"]} />
          <primitive object={nodes["N-TAN-LaughLine_3L"]} />
          <primitive object={nodes["N-BB-LaughLine_5L"]} />
          <primitive object={nodes["N-TAN-LaughLine_2L"]} />
          <primitive object={nodes["N-BB-LaughLine_4L"]} />
          <primitive object={nodes["N-TAN-LaughLine_1L"]} />
          <primitive object={nodes["N-TAN-Tail-LaughLine_1L"]} />
          <primitive object={nodes["N-TAN-Lip_Bot_Bot_2L"]} />
          <primitive object={nodes["N-TAN-Lip_Bot_Top_2L"]} />
          <primitive object={nodes["N-TAN-Cheek_1_1L"]} />
          <primitive object={nodes["N-BB-Cheek_1_1L"]} />
          <primitive object={nodes["N-TAN-Cheek_1_2L"]} />
          <primitive object={nodes["N-BB-Cheek_1_2L"]} />
          <primitive object={nodes["N-TAN-Cheek_1_3L"]} />
          <primitive object={nodes["N-TAN-Lip_Top_Top_1L"]} />
          <primitive object={nodes["N-TAN-Tail-Lip_Top_Top_1L"]} />
          <primitive object={nodes["N-TAN-Lip_Top_Bot_1L"]} />
          <primitive object={nodes["N-TAN-Tail-Lip_Top_Bot_1L"]} />
          <primitive object={nodes["N-TAN-LaughLine_Cheek_Across_1_1L"]} />
          <primitive object={nodes["N-TAN-LaughLine_Cheek_Across_1_2L"]} />
          <primitive object={nodes["N-TAN-LaughLine_Cheek_Across_2_1L"]} />
          <primitive object={nodes["N-TAN-LaughLine_Cheek_Across_2_2L"]} />
          <primitive object={nodes["N-TAN-Cheek_Cheek_Across_1L"]} />
          <primitive object={nodes["N-TAN-Cheek_Cheek_Across_2L"]} />
          <primitive object={nodes["N-TAN-Cheek_Jawline_AcrossL"]} />
          <primitive object={nodes["N-TAN-Tail-Cheek_Jawline_AcrossL"]} />
          <primitive object={nodes["N-BB-Lip_AboveM"]} />
          <primitive object={nodes["N-TAN-NoseRing_1L"]} />
          <primitive object={nodes["N-TAN-Nose_Lip_AcrossM"]} />
          <primitive object={nodes["N-BB-Nostril_2L"]} />
          <primitive object={nodes["N-TAN-NoseRing_2L"]} />
          <primitive object={nodes["N-TAN-Tail-NoseMidLine_1L"]} />
          <primitive object={nodes["N-TAN-Nose_Lip_AcrossL"]} />
          <primitive object={nodes["N-BB-LaughLine_3R"]} />
          <primitive object={nodes["N-TAN-NoseRing_3R"]} />
          <primitive object={nodes["N-BB-LaughLine_2R"]} />
          <primitive object={nodes["N-TAN-NoseRing_4R"]} />
          <primitive object={nodes["N-BB-LaughLine_1R"]} />
          <primitive object={nodes["N-TAN-NoseRing_5R"]} />
          <primitive object={nodes["N-TAN-Tail-NoseRing_5R"]} />
          <primitive object={nodes["N-TAN-NoseFront_1R"]} />
          <primitive object={nodes["N-BB-Nostril_1R"]} />
          <primitive object={nodes["N-TAN-NoseFront_2R"]} />
          <primitive object={nodes["N-TAN-Tail-NoseFront_2R"]} />
          <primitive object={nodes["N-BB-Forehead-_Top_1R"]} />
          <primitive object={nodes["N-TAN-Forehead_2_2R"]} />
          <primitive object={nodes["N-BB-Eyebrow_Top_1R"]} />
          <primitive object={nodes["N-TAN-Eyebrow_Across_1R"]} />
          <primitive object={nodes["N-BB-Eyebrow_Bot_1R"]} />
          <primitive object={nodes["N-TAN-Brow_Crease_Across_2R"]} />
          <primitive object={nodes["N-BB-EyeLid_Crease_2R"]} />
          <primitive object={nodes["N-TAN-Crease_Lid_Across_2R"]} />
          <primitive object={nodes["N-BB-Eyelid_Top_2R"]} />
          <primitive object={nodes["N-TAN-Tail-Crease_Lid_Across_2R"]} />
          <primitive object={nodes["N-BB-Forehead-_1R"]} />
          <primitive object={nodes["N-TAN-Forehead_1_2R"]} />
          <primitive object={nodes["N-BB-Eyebrow_1R"]} />
          <primitive object={nodes["N-TAN-Brow_Crease_Across_1R"]} />
          <primitive object={nodes["N-BB-EyeLid_Crease_1R"]} />
          <primitive object={nodes["N-TAN-Crease_Lid_Across_1R"]} />
          <primitive object={nodes["N-BB-Forehead-_Top_3R"]} />
          <primitive object={nodes["N-TAN-Forehead_4_2R"]} />
          <primitive object={nodes["N-BB-Eyebrow_Top_3R"]} />
          <primitive object={nodes["N-TAN-Eyebrow_Across_3R"]} />
          <primitive object={nodes["N-BB-Eyebrow_Bot_3R"]} />
          <primitive object={nodes["N-TAN-FaceRing_1R"]} />
          <primitive object={nodes["N-BB-NoseBridge_1R"]} />
          <primitive object={nodes["N-TAN-FaceRing_2R"]} />
          <primitive object={nodes["N-BB-NoseBridge_2R"]} />
          <primitive object={nodes["N-TAN-FaceRing_3R"]} />
          <primitive object={nodes["N-BB-Cheek_3_1R"]} />
          <primitive object={nodes["N-TAN-FaceRing_6R"]} />
          <primitive object={nodes["N-BB-Cheek_4_1R"]} />
          <primitive object={nodes["N-TAN-FaceRing_7R"]} />
          <primitive object={nodes["N-BB-Cheek_5_1R"]} />
          <primitive object={nodes["N-TAN-FaceRing_8R"]} />
          <primitive object={nodes["N-TAN-Eyebrow_Upper_1R"]} />
          <primitive object={nodes["N-TAN-Eyebrow_Upper_2R"]} />
          <primitive object={nodes["N-BB-Eyebrow_Top_2R"]} />
          <primitive object={nodes["N-TAN-Eyebrow_Upper_3R"]} />
          <primitive object={nodes["N-TAN-Eyebrow_Upper_4R"]} />
          <primitive object={nodes["N-TAN-Tail-Eyebrow_Upper_4R"]} />
          <primitive object={nodes["N-TAN-Brow_Crease_Across_4R"]} />
          <primitive object={nodes["N-BB-EyeLid_Crease_4R"]} />
          <primitive object={nodes["N-TAN-Crease_Lid_Across_4R"]} />
          <primitive object={nodes["N-BB-Eyelid_Top_4R"]} />
          <primitive object={nodes["N-TAN-Tail-Crease_Lid_Across_4R"]} />
          <primitive object={nodes["N-BB-Forehead-_Top_2R"]} />
          <primitive object={nodes["N-TAN-Forehead_3_2R"]} />
          <primitive object={nodes["N-TAN-Eyebrow_Across_2R"]} />
          <primitive object={nodes["N-BB-Eyebrow_Bot_2R"]} />
          <primitive object={nodes["N-TAN-Brow_Crease_Across_3R"]} />
          <primitive object={nodes["N-BB-EyeLid_Crease_3R"]} />
          <primitive object={nodes["N-TAN-Crease_Lid_Across_3R"]} />
          <primitive object={nodes["N-BB-Eyelid_Top_3R"]} />
          <primitive object={nodes["N-TAN-Tail-Crease_Lid_Across_3R"]} />
          <primitive object={nodes["N-BB-TempleR"]} />
          <primitive object={nodes["N-TAN-Temple_2R"]} />
          <primitive object={nodes["N-BB-JawLine_1R"]} />
          <primitive object={nodes["N-TAN-JawLine_1R"]} />
          <primitive object={nodes["N-BB-JawLine_2R"]} />
          <primitive object={nodes["N-TAN-JawLine_2R"]} />
          <primitive object={nodes["N-BB-JawLine_3R"]} />
          <primitive object={nodes["N-TAN-JawLine_3R"]} />
          <primitive object={nodes["N-BB-JawLine_4R"]} />
          <primitive object={nodes["N-TAN-JawLine_4R"]} />
          <primitive object={nodes["N-BB-JawLine_5R"]} />
          <primitive object={nodes["N-TAN-JawLine_5R"]} />
          <primitive object={nodes["N-TAN-Tail-JawLine_5R"]} />
          <primitive object={nodes["N-TAN-Cheek_Jawline_Across_1R"]} />
          <primitive object={nodes["N-TAN-Tail-Cheek_Jawline_Across_1R"]} />
          <primitive object={nodes["N-TAN-Eyelid_Top_2R"]} />
          <primitive object={nodes["N-TAN-Eyelid_Top_3R"]} />
          <primitive object={nodes["N-TAN-Eyelid_Top_4R"]} />
          <primitive object={nodes["N-BB-Eyelid_Top_5R"]} />
          <primitive object={nodes["N-TAN-Tail-Eyelid_Top_4R"]} />
          <primitive object={nodes["N-BB-Eyelid_Bot_2R"]} />
          <primitive object={nodes["N-TAN-Eyelid_Bot_2R"]} />
          <primitive object={nodes["N-BB-Eyelid_Bot_3R"]} />
          <primitive object={nodes["N-TAN-Eyelid_Bot_3R"]} />
          <primitive object={nodes["N-BB-Eyelid_Bot_4R"]} />
          <primitive object={nodes["N-TAN-Eyelid_Bot_4R"]} />
          <primitive object={nodes["N-BB-EyeLid_Crease_5R"]} />
          <primitive object={nodes["N-TAN-NoseBridge_2_2R"]} />
          <primitive object={nodes["N-TAN-NoseBridge_2_3R"]} />
          <primitive object={nodes["N-TAN-Tail-NoseBridge_2_3R"]} />
          <primitive object={nodes["N-TAN-NoseMidLine_3R"]} />
          <primitive object={nodes["N-TAN-NoseMidLine_2R"]} />
          <primitive object={nodes["N-TAN-NoseMidLine_1R"]} />
          <primitive object={nodes["N-BB-Lip_Top_TopR"]} />
          <primitive object={nodes["N-TAN-Lip_Top_AcrossR"]} />
          <primitive object={nodes["N-BB-Lip_Top_BotR"]} />
          <primitive object={nodes["N-TAN-Tail-Lip_Top_AcrossR"]} />
          <primitive object={nodes["N-TAN-Cheek_2_0R"]} />
          <primitive object={nodes["N-BB-Cheek_2_2R"]} />
          <primitive object={nodes["N-TAN-Cheek_2_3R"]} />
          <primitive object={nodes["N-TAN-Tail-Cheek_2_3R"]} />
          <primitive object={nodes["N-TAN-NoseCrease_0R"]} />
          <primitive object={nodes["N-TAN-Tail-NoseCrease_2R"]} />
          <primitive object={nodes["N-TAN-Cheek_3_0R"]} />
          <primitive object={nodes["N-BB-EyeLid_Crease_8R"]} />
          <primitive object={nodes["N-TAN-Cheek_3_1R"]} />
          <primitive object={nodes["N-TAN-Cheek_3_2R"]} />
          <primitive object={nodes["N-BB-Cheek_3_2R"]} />
          <primitive object={nodes["N-TAN-Cheek_Jawline_Across_3R"]} />
          <primitive object={nodes["N-TAN-Tail-Cheek_Jawline_Across_3R"]} />
          <primitive object={nodes["N-BB-EyeLid_Crease_10R"]} />
          <primitive object={nodes["N-TAN-Cheek_5_1R"]} />
          <primitive object={nodes["N-TAN-Cheek_5_2R"]} />
          <primitive object={nodes["N-TAN-Tail-Cheek_5_2R"]} />
          <primitive object={nodes["N-TAN-Cheek_4_2R"]} />
          <primitive object={nodes["N-BB-Cheek_4_2R"]} />
          <primitive object={nodes["N-TAN-Cheek_4_3R"]} />
          <primitive object={nodes["N-TAN-Tail-Cheek_4_3R"]} />
          <primitive object={nodes["N-TAN-Eyebrow_Lower_1R"]} />
          <primitive object={nodes["N-TAN-Eyebrow_Lower_2R"]} />
          <primitive object={nodes["N-TAN-Eyebrow_Lower_3R"]} />
          <primitive object={nodes["N-TAN-Eyebrow_Lower_4R"]} />
          <primitive object={nodes["N-TAN-Tail-Eyebrow_Lower_4R"]} />
          <primitive object={nodes["N-BB-Lip_Bot_BotR"]} />
          <primitive object={nodes["N-TAN-Lip_Bot_AcrossR"]} />
          <primitive object={nodes["N-BB-Lip_Bot_TopR"]} />
          <primitive object={nodes["N-TAN-Tail-Lip_Bot_AcrossR"]} />
          <primitive object={nodes["N-TAN-EyeLid_Crease_4R"]} />
          <primitive object={nodes["N-TAN-EyeLid_Crease_5R"]} />
          <primitive object={nodes["N-TAN-EyeLid_Crease_8R"]} />
          <primitive object={nodes["N-TAN-EyeLid_Crease_10R"]} />
          <primitive object={nodes["N-TAN-EyeLid_Crease_1R"]} />
          <primitive object={nodes["N-TAN-EyeLid_Crease_2R"]} />
          <primitive object={nodes["N-TAN-EyeLid_Crease_3R"]} />
          <primitive object={nodes["N-TAN-NoseBridge_1_2R"]} />
          <primitive object={nodes["N-TAN-NoseBridge_1_1R"]} />
          <primitive object={nodes["N-TAN-Tail-NoseBridge_1_1R"]} />
          <primitive object={nodes["N-BB-Chin_2R"]} />
          <primitive object={nodes["N-TAN-Cheek_1_4R"]} />
          <primitive object={nodes["N-TAN-Tail-Cheek_1_4R"]} />
          <primitive object={nodes["N-TAN-LaughLine_5R"]} />
          <primitive object={nodes["N-BB-LaughLine_7R"]} />
          <primitive object={nodes["N-TAN-LaughLine_4R"]} />
          <primitive object={nodes["N-BB-LaughLine_6R"]} />
          <primitive object={nodes["N-TAN-LaughLine_3R"]} />
          <primitive object={nodes["N-BB-LaughLine_5R"]} />
          <primitive object={nodes["N-TAN-LaughLine_2R"]} />
          <primitive object={nodes["N-BB-LaughLine_4R"]} />
          <primitive object={nodes["N-TAN-LaughLine_1R"]} />
          <primitive object={nodes["N-TAN-Tail-LaughLine_1R"]} />
          <primitive object={nodes["N-TAN-Lip_Bot_Bot_2R"]} />
          <primitive object={nodes["N-TAN-Lip_Bot_Top_2R"]} />
          <primitive object={nodes["N-TAN-Cheek_1_1R"]} />
          <primitive object={nodes["N-BB-Cheek_1_1R"]} />
          <primitive object={nodes["N-TAN-Cheek_1_2R"]} />
          <primitive object={nodes["N-BB-Cheek_1_2R"]} />
          <primitive object={nodes["N-TAN-Cheek_1_3R"]} />
          <primitive object={nodes["N-TAN-Lip_Top_Top_1R"]} />
          <primitive object={nodes["N-TAN-Tail-Lip_Top_Top_1R"]} />
          <primitive object={nodes["N-TAN-Lip_Top_Bot_1R"]} />
          <primitive object={nodes["N-TAN-Tail-Lip_Top_Bot_1R"]} />
          <primitive object={nodes["N-TAN-LaughLine_Cheek_Across_1_1R"]} />
          <primitive object={nodes["N-TAN-LaughLine_Cheek_Across_1_2R"]} />
          <primitive object={nodes["N-TAN-LaughLine_Cheek_Across_2_1R"]} />
          <primitive object={nodes["N-TAN-LaughLine_Cheek_Across_2_2R"]} />
          <primitive object={nodes["N-TAN-Cheek_Cheek_Across_1R"]} />
          <primitive object={nodes["N-TAN-Cheek_Cheek_Across_2R"]} />
          <primitive object={nodes["N-TAN-Cheek_Jawline_AcrossR"]} />
          <primitive object={nodes["N-TAN-Tail-Cheek_Jawline_AcrossR"]} />
          <primitive object={nodes["N-TAN-NoseRing_1R"]} />
          <primitive object={nodes["N-BB-Nostril_2R"]} />
          <primitive object={nodes["N-TAN-NoseRing_2R"]} />
          <primitive object={nodes["N-TAN-Tail-NoseMidLine_1R"]} />
          <primitive object={nodes["N-TAN-Nose_Lip_AcrossR"]} />
          <primitive object={nodes["IK-P-Pole-ForearmL"]} />
          <primitive object={nodes["IK-P-Hand_ParentL"]} />
          <primitive object={nodes["MSTR-P-Foot_ParentL"]} />
          <primitive object={nodes["IK-P-Pole-ForearmR"]} />
          <primitive object={nodes["IK-P-Hand_ParentR"]} />
          <primitive object={nodes["MSTR-P-Foot_ParentR"]} />
          <skinnedMesh
            name="GEO-rain_body"
            geometry={nodes["GEO-rain_body"].geometry}
            material={materials["MAT-rain.body"]}
            skeleton={nodes["GEO-rain_body"].skeleton}
          />
          <skinnedMesh
            name="GEO-rain_body001"
            geometry={nodes["GEO-rain_body001"].geometry}
            material={materials["MAT-rain.hands"]}
            skeleton={nodes["GEO-rain_body001"].skeleton}
          />
          <skinnedMesh
            name="GEO-rain_jeans"
            geometry={nodes["GEO-rain_jeans"].geometry}
            material={materials["MAT-rain.jeans"]}
            skeleton={nodes["GEO-rain_jeans"].skeleton}
          />
          <skinnedMesh
            name="GEO-rain_top"
            geometry={nodes["GEO-rain_top"].geometry}
            material={materials["MAT-rain.top"]}
            skeleton={nodes["GEO-rain_top"].skeleton}
          />
          <skinnedMesh
            name="GEO-rain_eyebrows"
            geometry={nodes["GEO-rain_eyebrows"].geometry}
            material={materials["MAT-rain.eyebrows"]}
            skeleton={nodes["GEO-rain_eyebrows"].skeleton}
          />
          <skinnedMesh
            name="GEO-rain_eyelashes"
            geometry={nodes["GEO-rain_eyelashes"].geometry}
            material={materials["MAT-rain.eyelashes"]}
            skeleton={nodes["GEO-rain_eyelashes"].skeleton}
          />
          <group name="GEO-rain_gums_lower">
            <skinnedMesh
              name="GEO-rain_gums_lower_Data"
              geometry={nodes["GEO-rain_gums_lower_Data"].geometry}
              material={materials["MAT-rain.gums"]}
              skeleton={nodes["GEO-rain_gums_lower_Data"].skeleton}
            />
            <skinnedMesh
              name="GEO-rain_gums_lower_Data_1"
              geometry={nodes["GEO-rain_gums_lower_Data_1"].geometry}
              material={materials["MAT-rain.teeth"]}
              skeleton={nodes["GEO-rain_gums_lower_Data_1"].skeleton}
            />
          </group>
          <group name="GEO-rain_gums_upper">
            <skinnedMesh
              name="GEO-rain_gums_upper_Data"
              geometry={nodes["GEO-rain_gums_upper_Data"].geometry}
              material={materials["MAT-rain.gums"]}
              skeleton={nodes["GEO-rain_gums_upper_Data"].skeleton}
            />
            <skinnedMesh
              name="GEO-rain_gums_upper_Data_1"
              geometry={nodes["GEO-rain_gums_upper_Data_1"].geometry}
              material={materials["MAT-rain.teeth"]}
              skeleton={nodes["GEO-rain_gums_upper_Data_1"].skeleton}
            />
          </group>
          <skinnedMesh
            name="GEO-rain_hair_ponytail"
            geometry={nodes["GEO-rain_hair_ponytail"].geometry}
            material={materials["MAT-rain.hair"]}
            skeleton={nodes["GEO-rain_hair_ponytail"].skeleton}
          />
          <skinnedMesh
            name="GEO-rain_hair_strand"
            geometry={nodes["GEO-rain_hair_strand"].geometry}
            material={materials["MAT-rain.hair"]}
            skeleton={nodes["GEO-rain_hair_strand"].skeleton}
          />
          <skinnedMesh
            name="GEO-rain_hairband"
            geometry={nodes["GEO-rain_hairband"].geometry}
            material={materials["MAT-rain.hairband"]}
            skeleton={nodes["GEO-rain_hairband"].skeleton}
          />
          <skinnedMesh
            name="GEO-rain_head"
            geometry={nodes["GEO-rain_head"].geometry}
            material={materials["MAT-rain.head"]}
            skeleton={nodes["GEO-rain_head"].skeleton}
            morphTargetDictionary={nodes["GEO-rain_head"].morphTargetDictionary}
            morphTargetInfluences={nodes["GEO-rain_head"].morphTargetInfluences}
          />
          <group name="GEO-rain_shoes">
            <skinnedMesh
              name="GEO-rain_shoes_Data"
              geometry={nodes["GEO-rain_shoes_Data"].geometry}
              material={materials["MAT-rain.shoes"]}
              skeleton={nodes["GEO-rain_shoes_Data"].skeleton}
              morphTargetDictionary={
                nodes["GEO-rain_shoes_Data"].morphTargetDictionary
              }
              morphTargetInfluences={
                nodes["GEO-rain_shoes_Data"].morphTargetInfluences
              }
            />
            <skinnedMesh
              name="GEO-rain_shoes_Data_1"
              geometry={nodes["GEO-rain_shoes_Data_1"].geometry}
              material={materials["MAT-rain.metal"]}
              skeleton={nodes["GEO-rain_shoes_Data_1"].skeleton}
              morphTargetDictionary={
                nodes["GEO-rain_shoes_Data_1"].morphTargetDictionary
              }
              morphTargetInfluences={
                nodes["GEO-rain_shoes_Data_1"].morphTargetInfluences
              }
            />
            <skinnedMesh
              name="GEO-rain_shoes_Data_2"
              geometry={nodes["GEO-rain_shoes_Data_2"].geometry}
              material={materials["MAT-rain.socks"]}
              skeleton={nodes["GEO-rain_shoes_Data_2"].skeleton}
              morphTargetDictionary={
                nodes["GEO-rain_shoes_Data_2"].morphTargetDictionary
              }
              morphTargetInfluences={
                nodes["GEO-rain_shoes_Data_2"].morphTargetInfluences
              }
            />
            <skinnedMesh
              name="GEO-rain_shoes_Data_3"
              geometry={nodes["GEO-rain_shoes_Data_3"].geometry}
              material={materials["MAT-rain.laces"]}
              skeleton={nodes["GEO-rain_shoes_Data_3"].skeleton}
              morphTargetDictionary={
                nodes["GEO-rain_shoes_Data_3"].morphTargetDictionary
              }
              morphTargetInfluences={
                nodes["GEO-rain_shoes_Data_3"].morphTargetInfluences
              }
            />
          </group>
          <skinnedMesh
            name="GEO-rain_eyes"
            geometry={nodes["GEO-rain_eyes"].geometry}
            material={materials["MAT-rain.eyes"]}
            skeleton={nodes["GEO-rain_eyes"].skeleton}
            morphTargetDictionary={nodes["GEO-rain_eyes"].morphTargetDictionary}
            morphTargetInfluences={nodes["GEO-rain_eyes"].morphTargetInfluences}
          />
          <skinnedMesh
            name="GEO-rain_hair_main"
            geometry={nodes["GEO-rain_hair_main"].geometry}
            material={materials["MAT-rain.hair"]}
            skeleton={nodes["GEO-rain_hair_main"].skeleton}
            morphTargetDictionary={
              nodes["GEO-rain_hair_main"].morphTargetDictionary
            }
            morphTargetInfluences={
              nodes["GEO-rain_hair_main"].morphTargetInfluences
            }
          />
          <skinnedMesh
            name="GEO-rain_tongue"
            geometry={nodes["GEO-rain_tongue"].geometry}
            material={materials["MAT-rain.tongue"]}
            skeleton={nodes["GEO-rain_tongue"].skeleton}
            morphTargetDictionary={
              nodes["GEO-rain_tongue"].morphTargetDictionary
            }
            morphTargetInfluences={
              nodes["GEO-rain_tongue"].morphTargetInfluences
            }
          />
        </group>
        <group name="Sun" position={[0, 5.26, 0]} rotation={[1.06, 0, 0]}>
          <directionalLight
            name="Sun_Orientation"
            intensity={1}
            color="#000aff"
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[0, 0, -1]} />
          </directionalLight>
        </group>
        {/* <group name="Spot" position={[0.75, 3.89, 4.25]} rotation={[0.83, 0, 0]}>
          <spotLight name="Spot_Orientation" intensity={1000} angle={0.14} penumbra={0.87} decay={2} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[0, 0, -1]} />
          </spotLight>
        </group> */}
        <group name="Camera" position={[0, 0.91, 2.03]} rotation={[1.52, 0, 0]}>
          <PerspectiveCamera
            name="Camera_Orientation"
            makeDefault={false}
            far={1000}
            near={0.1}
            fov={60.28}
            rotation={[-Math.PI / 2, 0, 0]}
          />
        </group>
        <group name="Spot001" position={[0, 2.21, -0.47]}>
          <spotLight
            name="Spot001_Orientation"
            intensity={107.4}
            angle={Math.PI / 8}
            penumbra={0.15}
            decay={2}
            color="#ff00d6"
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group position={[0, 0, -1]} />
          </spotLight>
        </group>
        <mesh
          name="Cylinder"
          geometry={nodes.Cylinder.geometry}
          material={materials["Material.003"]}
          position={[0, -0.06, 0]}
          scale={[0.53, 0.09, 0.53]}
        />
        <mesh
          name="Cylinder001"
          geometry={nodes.Cylinder001.geometry}
          material={materials["Material.004"]}
          position={[0, 0.1, 0]}
          scale={[0.49, 0.08, 0.49]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/rain_rig.glb");
